"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var num1 = 56;
var num2 = 35;
console.log(num1);
console.log(num2);
num1 = 28;
// num2 = 18;
console.log(num1);
console.log(num2);
